bind = $mainMod, Return, exec, konsole
bind = $mainMod, T, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, Space, exec, pkill wofi || wofi --show drun
bind = $mainMod, V, togglefloating,
bind = $mainMod+Shift, F, fullscreen,
bind = $mainMod, P, pseudo,
bind = $mainMod+Shift, J, togglesplit,

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod+Shift, left, movewindow, l
bind = $mainMod+Shift, right, movewindow, r
bind = $mainMod+Shift, up, movewindow, u
bind = $mainMod+Shift, down, movewindow, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod+Shift, 1, movetoworkspace, 1
bind = $mainMod+Shift, 2, movetoworkspace, 2
bind = $mainMod+Shift, 3, movetoworkspace, 3
bind = $mainMod+Shift, 4, movetoworkspace, 4
bind = $mainMod+Shift, 5, movetoworkspace, 5
bind = $mainMod+Shift, 6, movetoworkspace, 6
bind = $mainMod+Shift, 7, movetoworkspace, 7
bind = $mainMod+Shift, 8, movetoworkspace, 8
bind = $mainMod+Shift, 9, movetoworkspace, 9
bind = $mainMod+Shift, 0, movetoworkspace, 10

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod+Shift, S, exec, grim -g "$(slurp)" - | wl-copy

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod+Shift, L, exec, loginctl lock-session
bind = $mainMod, Escape, exec, ~/.config/hypr/setup-monitors.sh

bind = $mainMod, Tab, cyclenext
bind = $mainMod+Shift, Tab, cyclenext, prev

bindl = , switch:on:Lid Switch, exec, systemctl suspend
bind = $mainMod, F2, exec, systemctl suspend
